Models/ErrorViewModel.cs
namespace WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MovieModel.cs
namespace WebApp.Models
{
    public class MovieModel
    {

        public int MovieID { get; set; }
        public string Title { get; set; }
        public int ReleaseYear { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;
using System.Data;
using WebApp.Models;


namespace WebApp.Controllers
{
    public class MovieController : Controller
    {
        IConfiguration _configuration;
        SqlConnection _Connection;


        public MovieController(IConfiguration configuration)
        {
            _configuration = configuration;
            _Connection = new SqlConnection(_configuration.GetConnectionString("Practice"));
        }


        public List<MovieModel> GetMovies()
        {
            List<MovieModel> Movies = new();
            _Connection.Open();
            SqlCommand cmd = new SqlCommand("FETCH_MOVIES",_Connection);
            cmd.CommandType = CommandType.StoredProcedure;
            SqlDataReader reader = cmd.ExecuteReader();

            while(reader.Read())
            {
                MovieModel movie = new();
                movie.MovieID = (int)reader["MovieID"];
                movie.Title = (string)reader["Title"];
                movie.ReleaseYear = (int)reader["ReleaseYear"];
                movie.Genre = (string)reader["Genre"];
                movie.Director = (string)reader["Director"];
                Movies.Add(movie);
            }

            reader.Close();
            _Connection.Close();

            return Movies;
            
        }

        // GET: MovieController
        public ActionResult Index()
        {

            return View(GetMovies());
        }

        // GET: MovieController/Details/5
        public ActionResult Details(int id)
        {
            return View(GetMovie(id));
        }

        // GET: MovieController/Create
        public ActionResult Create()
        {
            return View();
        }

        void InsertMovie(MovieModel Movie)
        {
            _Connection.Open();
            SqlCommand cmd = new SqlCommand("ADD_MOVIE", _Connection);
            cmd.CommandType = CommandType.StoredProcedure;

            cmd.Parameters.AddWithValue("@Title", Movie.Title);
            cmd.Parameters.AddWithValue("@ReleaseYear", Movie.ReleaseYear);
            cmd.Parameters.AddWithValue("@Genre", Movie.Genre);
            cmd.Parameters.AddWithValue("@Director", Movie.Director);

            cmd.ExecuteNonQuery();

            _Connection.Close();

        }

        // POST: MovieController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MovieModel Movie)
        {
            try
            {
                InsertMovie(Movie);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
                return View();
            }
        }

        MovieModel GetMovie(int id)
        {
            _Connection.Open();
            SqlCommand cmd = new SqlCommand("GET_MOVIE", _Connection);
            cmd.CommandType = CommandType.StoredProcedure;

            cmd.Parameters.AddWithValue("@MovieID", id);

            SqlDataReader reader = cmd.ExecuteReader();

            MovieModel movie = new();

            while (reader.Read())
            {
                
                movie.MovieID = (int)reader["MovieID"];
                movie.Title = (string)reader["Title"];
                movie.ReleaseYear = (int)reader["ReleaseYear"];
                movie.Genre = (string)reader["Genre"];
                movie.Director = (string)reader["Director"];
            }
            return movie;
        }


            // GET: MovieController/Edit/5
            public ActionResult Edit(int id)
        {
            //Console.WriteLine(id);
            return View(GetMovie(id));
        }

        void UpdateMovie(int id, MovieModel Movie)
        {
            _Connection.Open();
            SqlCommand cmd = new SqlCommand("EDIT_MOVIE", _Connection);
            cmd.CommandType = CommandType.StoredProcedure;

            cmd.Parameters.AddWithValue("@Title", Movie.Title);
            cmd.Parameters.AddWithValue("@ReleaseYear", Movie.ReleaseYear);
            cmd.Parameters.AddWithValue("@Genre", Movie.Genre);
            cmd.Parameters.AddWithValue("@Director", Movie.Director);
            cmd.Parameters.AddWithValue("@MovieID", id);

            cmd.ExecuteNonQuery();

            _Connection.Close();
        }

        // POST: MovieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MovieModel Movie)
        {
            try
            {
                UpdateMovie(id, Movie);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MovieController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(GetMovie(id));
        }

        // POST: MovieController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, MovieModel Movie)
        {
            try
            {
                _Connection.Open();
                SqlCommand cmd = new SqlCommand("DELETE FROM Movies WHERE MovieID=@MovieID",
                    _Connection);

                cmd.Parameters.AddWithValue("@MovieID", id);
                cmd.ExecuteNonQuery();

                _Connection.Close();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Movie/Create.cshtml
@model WebApp.Models.MovieModel

@{
    ViewData["Title"] = "Add Movie";
}

<h1>Create New Movie</h1>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
         
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseYear" class="control-label"></label>
                <input asp-for="ReleaseYear" class="form-control" />
                <span asp-validation-for="ReleaseYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group mt-3">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Movie/Delete.cshtml
@model WebApp.Models.MovieModel

@{
    ViewData["Title"] = "View";
}

<h3>Are you sure you want to delete this?</h3>
<br />
<div>
    <h4>@Model.Title</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MovieID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MovieID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Director)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Movie/Details.cshtml
@model WebApp.Models.MovieModel

@{
    ViewData["Title"] = "Movie - Detail";
}

<h1>Movie - Detail</h1>
<br />

<div>
    <h4>@Model.Title</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MovieID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MovieID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ReleaseYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Director)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Director)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MovieID }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/Movie/Edit.cshtml
@model WebApp.Models.MovieModel

@{
    ViewData["Title"] = "Edit Movie";
}

<h1>Edit Movie</h1>

<br />
<h5>@Model.Title</h5>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ReleaseYear" class="control-label"></label>
                <input asp-for="ReleaseYear" class="form-control" />
                <span asp-validation-for="ReleaseYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genre" class="control-label"></label>
                <input asp-for="Genre" class="form-control" />
                <span asp-validation-for="Genre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Director" class="control-label"></label>
                <input asp-for="Director" class="form-control" />
                <span asp-validation-for="Director" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Movie/Index.cshtml
@model IEnumerable<WebApp.Models.MovieModel>

@{
    ViewData["Title"] = "Movies List";
}

<h1>All Movies</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MovieID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Director)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MovieID)
            </td>
            <td>
                    @Html.ActionLink(item.Title, "Details", new { id=item.MovieID })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                    @Html.ActionLink("Edit",  "Edit", new { id=item.MovieID}) |
                     
                    @Html.ActionLink("Delete", "Delete", new { id=item.MovieID })
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>